### ISSUE TITLE
Socketio swift + flask-socketio connect problems

### ISSUE THREAD

**Issue by ludusrusso** [socketio/socket.io-client-swift#154]
I'm using the flask-socketio server in combination with js socket.io-client that works very well, however, I'm not able to connect with socket.io-client.swift.

This is the code I use in js:
```javascript
var path = 'http://localhost:5000'
    var socket = io.connect(path);
    console.log(path)
    socket.on('connect', function() {
        socket.emit('connected')
        console.log('connected')
    });
```
and this in swift

```swift

    let socket = SocketIOClient(socketURL: "http://localhost:5000", options:["log": true])
...
func socketHandler() {
        socket.on("connect") {data, ack in
            println("socket connected")
        }
        
        self.socket.on("added") {data, ack in
            println("added")
        }
        
        self.socket.on("error") {data, ack in
            println("error")
        }
        
        self.socket.onAny{println("got event: \($0.event) with items \($0.items)")}
    }

...
 override func viewDidLoad() {
      ...
        
        socketHandler()
        self.socket.connect()
...
```

Here is the logs of swift client
```
2015-08-31 10:51:34.281 test[34757:3990559] SocketClient: Adding handler for event: connect
2015-08-31 10:51:34.321 test[34757:3990559] SocketClient: Adding handler for event: added
2015-08-31 10:51:34.323 test[34757:3990559] SocketClient: Adding handler for event: error
2015-08-31 10:51:34.323 test[34757:3990559] SocketClient: Adding engine
2015-08-31 10:51:34.323 test[34757:3990559] SocketEngine: Starting engine
2015-08-31 10:51:34.323 test[34757:3990559] SocketEngine: Handshaking
2015-08-31 10:51:34.323 test[34757:3990559] SocketEngine: Doing polling request
2015-08-31 10:51:34.368 test[34757:3990561] SocketEngine: Got polling response

```

However, the " println("socket connected")" is not called.

The http request the two codes generate are different:

```
GET /socket.io/?EIO=3&transport=polling&t=1441010930064-34&sid=27b39693eafe4017a3677dc105cd1ccf    # Javascript
GET /socket.io/?transport=polling&b64=1 # Swift
```

**Comment by nuclearace** [comment]
What version of the JavaScript client are you using?

**Comment by ludusrusso** [comment]
1.3.6, with [flask-socketio compatible with socket.io 1](https://github.com/miguelgrinberg/Flask-SocketIO/tree/v1.0)

**Comment by nuclearace** [comment]
Is there any kind of logging you can turn on for the server?

**Comment by ludusrusso** [comment]
Not so much,
this is what I get when the swift client connects:
```
client connected
127.0.0.1 - - [31/Aug/2015 14:21:36] "GET /socket.io/?transport=polling&b64=1 HTTP/1.1" 200 -
```
and this is the one from javascript
```
client connected
127.0.0.1 - - [31/Aug/2015 14:22:13] "GET /socket.io/?EIO=3&transport=polling&t=1441023733317-0 HTTP/1.1" 200 -
```

The server seems to correct recognize the connection, but I'm not able to capture messages from the client.

**Comment by nuclearace** [comment]
What happens if you try to force websockets on the client?

**Comment by nuclearace** [comment]
Also, this wouldn't be the first time I've seen a socket.io server not properly handle missing request fields. https://github.com/socketio/socket.io-client-swift/issues/100

**Comment by ludusrusso** [comment]
forcing websocket I got this:
```
2015-08-31 17:01:25.717 test[41184:4220660] SocketClient: Adding handler for event: connect
2015-08-31 17:01:25.717 test[41184:4220660] SocketClient: Adding handler for event: added
2015-08-31 17:01:25.718 test[41184:4220660] SocketClient: Adding handler for event: error
2015-08-31 17:01:25.718 test[41184:4220660] SocketClient: Adding engine
2015-08-31 17:01:25.718 test[41184:4220660] SocketEngine: Starting engine
2015-08-31 17:01:25.718 test[41184:4220660] SocketEngine: Handshaking
2015-08-31 17:01:25.791 test[41184:4220682] ERROR SocketClient: Invalid HTTP upgrade
2015-08-31 17:01:25.792 test[41184:4220682] SocketClient: Handling event: error with data: (
    "Invalid HTTP upgrade"
)
2015-08-31 17:01:25.793 test[41184:4220682] SocketClient: Handling event: reconnect with data: (
    "Invalid HTTP upgrade"
)
2015-08-31 17:01:25.793 test[41184:4220682] SocketClient: Starting reconnect
2015-08-31 17:01:25.793 test[41184:4220682] SocketClient: Trying to reconnect
2015-08-31 17:01:25.794 test[41184:4220682] SocketClient: Handling event: reconnectAttempt with data: (
    "-1"
)
2015-08-31 17:01:25.796 test[41184:4220682] SocketClient: Adding engine
2015-08-31 17:01:25.798 test[41184:4220682] SocketEngine: Starting engine
2015-08-31 17:01:25.798 test[41184:4220682] SocketEngine: Handshaking
2015-08-31 17:01:25.800 test[41184:4220682] SocketEngine: Engine is being deinit
2015-08-31 17:01:25.805 test[41184:4220682] ERROR SocketClient: Invalid HTTP upgrade
2015-08-31 17:01:25.805 test[41184:4220682] SocketClient: Handling event: error with data: (
    "Invalid HTTP upgrade"
)
got event: error with items Optional((
    "Invalid HTTP upgrade"
))
error
got event: reconnect with items Optional((
    "Invalid HTTP upgrade"
))
got event: reconnectAttempt with items Optional((
    "-1"
))
got event: error with items Optional((
    "Invalid HTTP upgrade"
))
```

Ok, I'm trying to understand how flask-socketio works!

**Comment by nuclearace** [comment]
Well with that it looks like whatever WebSocket library flask is using doesn't like WebSockets. Or it's because the flask-socketio server isn't handling the request properly

**Comment by miguelgrinberg** [comment]
@ludusrusso There's logging support in the server side. Add `logger=True, engineio_logger=True` arguments to your server constructor to get logging for Socket.IO and Engine.IO.

I have been able to use the Swift client with long-polling. Forcing WebSocket is not going to work, the Engine.IO server expects the connection to be established with long-polling and then upgraded to WS, exactly like it happens with the JS client. I have not tried the WebSocket upgrades myself, but I know of a user that has been able to get WS working without the force websocket flag. I need to experiment more with the Swift client, I have literally tested it for a couple of hours, so haven't been able to run as much testing as I need.

**Comment by nuclearace** [comment]
On a standard node.js socket.io server, if the server is configured to use websockets you can have the client only use websockets.

```javascript
var socket = require('socket.io-client')("http://localhost:8080", {transports: ["websocket"]})
```
And this is reflected in the Swift client.

```swift
let socket = SocketIOClient(socketURL: "localhost:8080", opts: ["forceWebsockets": true])
```

**Comment by miguelgrinberg** [comment]
@nuclearace I was not aware this was allowed in the JS client. I implemented the Python server from the specs, which clearly state the client must connect on long-polling and then upgrade. I'll look into the direct websocket connection.

**Comment by ludusrusso** [comment]
Ok, 
after a full reinstallation of the entire python virtual env I solved the problem.
I don't know if there was a problem in the previous installation or if the last commits of @miguelgrinberg fixed it. 
Anyway I think I can close the issue

**Comment by manju1981** [comment]
Hi Miguel,

I too facing same issue as above below is the server side log. Steps to recreate

1. Pythond 2.7.10
2. created virtual environment and below is python code

from flask import Flask
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@socketio.on('connect')
def test_connect():
    print('Client connected')
    emit('message', {'data': 'Connected'})

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected')

if __name__ == '__main__':
    app.debug = True
    socketio.run(app, host='127.0.0.1',port=5000,  logger=True, engineio_logger=True)
 
<b> Even i am using swift socket io client <b>
(sandalmatching)INmanjurn:src manjurn$ python WebSocket.py
Server initialized for threading.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Server initialized for threading.
1639dab20ba94d63bce087ecd26f04e2: Sending packet OPEN with {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': [], 'sid': '1639dab20ba94d63bce087ecd26f04e2'}
Client connected
emitting event "message" to 1639dab20ba94d63bce087ecd26f04e2 [/]
1639dab20ba94d63bce087ecd26f04e2: Sending packet MESSAGE with 2["message",{"data":"Connected"}]
1639dab20ba94d63bce087ecd26f04e2: Sending packet MESSAGE with 0
1639dab20ba94d63bce087ecd26f04e2: Received request to upgrade to websocket
127.0.0.1 - - [12/Sep/2015 21:23:14] "GET /socket.io/?transport=websocket HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/engineio/middleware.py", line 32, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/socketio/server.py", line 305, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/engineio/server.py", line 215, in handle_request
    transport, b64)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/engineio/server.py", line 280, in _handle_connect
    s.handle_get_request(environ, start_response)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/engineio/socket.py", line 75, in handle_get_request
    start_response)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/engineio/socket.py", line 109, in _upgrade_websocket
    self.server.async['websocket_class'])
TypeError: getattr(): attribute name must be string

**Comment by miguelgrinberg** [comment]
@manju1981 you are running in "threading" mode, which does not support the websocket transport. I will see if I can make the error message more clear.

Also, please write a bug in my Socket.IO project(s) for any problems you have with my Python server.

**Comment by manju1981** [comment]
@miguelgrinberg Any work around to get it working?. I am going to raise this bug in Socket.IO project.

**Comment by jigarPatel37** [comment]
I am using Socket.IO-Client-Swift with pods in my chat aplication in xcode 8.0 with swift 3.0.
It's gives some error like as under is there any solution for this. And application will crash....

ERROR SocketEnginePolling: The network connection was lost.
ERROR SocketEngine: The network connection was lost.
ERROR SocketIOClient: The network connection was lost.

ERROR SocketEnginePolling: Could not connect to the server.
ERROR SocketEngine: Could not connect to the server.
ERROR SocketIOClient: Could not connect to the server.

ERROR SocketEngine: Session ID unknown
ERROR SocketIOClient: Session ID unknown
